### PR TITLE
Update NuGet packages to latest versions, test still pass.

### PR DESCRIPTION
**Pull request by newmancodes**
I'm seeing some assembly version conflicts so figured I'd try to help. Fairly new to this so if this isn't helpful then no hard feelings.

Loaded the solution into Visual Studio, managed NuGet packages and just upgraded everything. Had some build errors requiring that IStateProviderReplica2 be used instead of IStateProviderReplica, I've made those changes and everything builds and test suite pass.

### CODE REVIEW

**Comment by heavenwing** [comment]
Latest nuget version (3.0) have released.

**Comment by newmancodes** [comment]
I've updated to SF 6.1

**Comment by snaits** [comment]
Anyone, please let me know if I can help to move this along, I'm looking forward to updating to SF 6.1 😄

**Comment by alexmg** [comment]
Thanks for the PR @goodisontoffee. I'm currently migrating the project to .NET Core with the intent of targeting `netstandard2.0` and `net452`.

**Comment by alexmg** [comment]
Thank you all for your patience. It has been a busy week.

The projects have been upgraded to .NET Core in beb6172427916f442ba57f69babae28f3e53beb1 and now targets `netstandard2.0` and `net452`. Build and unit tests are passing on both target frameworks.

Please grab the latest CI package from our MyGet feed and let me know how it goes for you. Hopefully things go well and this can move quickly to release.

https://www.myget.org/F/autofac/api/v3/index.json

I have bumped the package version to `2.0.0` for this release. The first `2.0.0` dev build on the MyGet feed is `2.0.0-develop-00034`.

**Comment by alexmg** [comment]
I am closing this PR and have created issue #27 to cover the Service Fabric 6.1 upgrade. Please report any feedback over on that issue is possible.

**Pull request closed without merging**
